version: '3'

services:
  history-etl:
    image: kinecosystem/history-collector:20190314kin2
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: ''
      PYTHON_PASSWORD: ''
      LAMBDA_NAME: ''
      LAMBDA_REGION: ''
      EMAIL_SMTP: ''
      EMAIL_ACCOUNT: ''
      EMAIL_PASSWORD: ''
      EMAIL_RECIPIENTS: ''
      KIN_ISSUER: 'GDF42M3IPERQCBLWFEZKQRK77JQ65SCKTU3CW36HZVCX7XX5A5QXZIVK'
      FIRST_FILE: '0000003f'
      NETWORK_PASSPHRASE: 'Public Global Kin Ecosystem Network ; June 2018'
      MAX_RETRIES: 5
      BUCKET_NAME: 'stellar-core-ecosystem-6145'
      CORE_DIRECTORY: ''
      LOG_LEVEL: 'INFO'
      APP_ID:
